/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppEmpty: typeof import('./../components/common/AppEmpty.vue')['default']
    AppError: typeof import('./../components/common/AppError.vue')['default']
    AppLoading: typeof import('./../components/common/AppLoading.vue')['default']
    AppNavbar: typeof import('./../components/common/AppNavbar.vue')['default']
    AppSafeArea: typeof import('./../components/common/AppSafeArea.vue')['default']
    CategorySwitch: typeof import('./../components/category/CategorySwitch.vue')['default']
    CustomTabbar: typeof import('./../components/tabbar/CustomTabbar.vue')['default']
    DailyQuestionCard: typeof import('./../components/question/DailyQuestionCard.vue')['default']
    ProgressBar: typeof import('./../components/question/ProgressBar.vue')['default']
    QuestionCard: typeof import('./../components/question/QuestionCard.vue')['default']
    RandomExamPopup: typeof import('./../components/exam/RandomExamPopup.vue')['default']
    SearchBar: typeof import('./../components/search/SearchBar.vue')['default']
  }
}
